// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import { Loader } from "@googlemaps/js-api-loader"

import { application } from "./application"

import HelloController from "./hello_controller"

application.register("hello", HelloController)

const loader = new Loader({
  apiKey: "GOOGLE_MAPS_API_KEY",
  version: "weekly",
});

// Initialize and add the map
let map;

async function initMap() {
  // The location of Uluru
  // Request needed libraries.
  //@ts-ignore
  const { Map } = await google.maps.importLibrary("maps");
  const { AdvancedMarkerElement } = await google.maps.importLibrary("marker");
  const beachInstances = []
  // The map, centered at Uluru
  map = new Map(document.getElementById("map"), {
    zoom: 4,
    center: { lat: -25.363, lng: 131.044 },
    mapId: "DEMO_MAP_ID",
  });
  fetch('/beaches.json')
  .then(response => response.json())
  .then(beaches => {
    // Iterate over the beaches array and create beach instances
    beaches.forEach(beach => {
      const beachInstance = new google.maps.Marker({
        position: {
          lat: beach.latitude,
          lng: beach.longitude
        },
        map: map,
        title: beach.name
      });

      // Add the beach instance to the array
      beachInstances.push(beachInstance);
    });
  })
}

initMap();
// Global variables
